config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "trees#index"
  get 'get_family', to: 'trees#get_family'
  resources :people, :families, :trees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/family.rb
class Family
  include Mongoid::Document
  include Mongoid::Timestamps
  field :surname, type: String

  validates :surname, presence: true, uniqueness: true
end

app/models/person.rb
class Person
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :description, type: String
  field :birth_date, type: String
  field :death_date, type: String
  field :family, type: String
  field :father, type: String
  field :mother, type: String
  field :married_on, type: Array

  
  validates :name, presence: true
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  include Mongoid::Timestamps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: [:edit, :update]
  
  def index
    @families = Family.all
  end
  
  def new 
    @family = Family.new
  end

  def create
    @family = Family.new(family_params)

    if @family.save
      redirect_to families_path, notice: 'Семья сохранена'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @family.update(family_params)
      redirect_to families_path
    else
      render :edit
    end
  end

  private

  def family_params
    params.require(:family).permit(:surname)
  end

  def set_family
    @family = Family.find(params[:id])
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :load_person, only: [:show, :edit, :update, :destroy]

  def index
    @people = Person.all.order_by(family: :desc)
    @families = Family.all
  end

  def show
  end
  
  def new
    @person = Person.new
    @people = Person.all
    @families = Family.all
  end

  def edit
    @people = Person.where(family: @person.family)
    @families = Family.all
  end

  def create 
    @person = Person.new(person_params)
    
    if @person.save
      redirect_to people_path, notice: 'Person saved'
    else
      @people = Person.all
      @families = Family.all
      render :new
    end
  end

  def update
    if @person.update(person_params)
      redirect_to people_path
    else
      render :edit
    end
  end

  def destroy
    @person.destroy
    redirect_to people_path, notice: 'Человек удален'
  end

  private
  
  def load_person 
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:name, :description, :birth_date, :death_date, :family, :father, :mother, married_on: [])
  end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  def index
    @families = Family.all
  end

  def get_family
    arr_people = []
    @people = Person.where(family: params[:id])
    @people.each do |p|
      arr_people << {
        id: p.id.to_s, 
        name: p.name, 
        parent: p.father, 
        mother: p.mother,
        partners: p.married_on.present? ? p.married_on : [],
        birth_date: p.birth_date,
        death_date: p.death_date,
      }
    end
    respond_to do |format|
      format.js
      format.html { render turbo_stream: turbo_stream.replace(
        "table_of_people", 
        partial: "people/table", 
        locals: { resource: params[:id] == '' ? Person.all : @people }
      ) }
      format.json { render json: arr_people }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/families/_form.html.slim
= form_with class: "form-style", model: @family do |f|
  h1 Новый род
  ul 
    li
      = f.label :surname, 'Фамилия'
      = f.text_field :surname
    li  
      = f.submit 'Сохранить', class: 'btn'
  

app/views/families/edit.html.slim
= render 'shared/errors', resource: @family 

= link_to 'Назад', families_path, class: 'btn'

= render "form" 

app/views/families/index.html.slim
h3 Семьи
= link_to 'Назад', trees_path, class: 'btn'
p = link_to 'Новая семья', new_family_path, class: 'btn'

table
  thead
    tr
      th Семья
      th Люди
      th
  tbody
    - @families.each do |family|
      tr
        td = "#{family.surname}"
        td = "#{ Person.where(family: family.id.to_s).map { |p| p.name } }"
        td 
          = link_to 'Удалить', family, data: { turbo_method: :delete, turbo_confirm: 'Вы уверены?' }
          br 
          = link_to 'Изменить', edit_family_path(family)

app/views/families/new.html.slim
= render 'shared/errors', resource: @family 

= link_to 'Назад', families_path, class: 'btn'

= render "form" 

app/views/layouts/_loading.html.slim
div class="loader" id='loader' style="display: none"
  div class="loader-inner"
    div class="loader-line-wrap"
      div class="loader-line"
    div class="loader-line-wrap"
      div class="loader-line"
    div class="loader-line-wrap"
      div class="loader-line"
    div class="loader-line-wrap"
      div class="loader-line"
    div class="loader-line-wrap"
      div class="loader-line"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rodoslov</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <h2><%= link_to 'L O T U S', trees_path %></h2>
      <nav class="menu menu-1">
        <ul>
          <li><%= link_to 'Люди', people_path%></li>
          <li><%= link_to 'Семьи', families_path%></li>
        </ul>
      </nav>
    </header>
    <div class="main"> 
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= render "layouts/loading" %>
      <%= yield %>
    </div>
    <footer>
        <h2>Contacts</h2>
        <a href="https://github.com/Croud9/Rood" target="_blank">Create by Svyat Melihov | Croud9</a>
    </footer>
  </body>
</html>

app/views/people/_form.html.slim
= form_with class: "form-style", model: @person do |f|
  h1 Новый человек
  ul
    li
      = f.label :name, 'ФИО'
      = f.text_field :name
    li
      = f.label :birth_date, 'Дата рождения'
      = f.text_field :birth_date
    li
      = f.label :death_date, 'Дата смерти'
      = f.text_field :death_date
    li
      = f.label :description, 'Описание'
      = f.text_area :description
    li
      = f.label :family, 'Семья'
      = f.select :family, options_from_collection_for_select(@families, :id, :surname, @person.family), { prompt: "Выберите" }
    li
      = f.label :father, 'Отец'
      = f.select :father, options_from_collection_for_select(@people, :id, :name, @person.father), { prompt: "Выберите"}
    li
      = f.label :mother, 'Мать'
      = f.select :mother, options_from_collection_for_select(@people, :id, :name, @person.mother), { prompt: "Выберите"}
    li
      = f.label :married_on, 'В браке с'
      = f.select :married_on, options_from_collection_for_select(@people, :id, :name, @person.married_on), { prompt: "Выберите", include_hidden: false }, { multiple: true, size: 10}
    li      
      = f.submit 'Сохранить', class: 'btn'

app/views/people/_table.html.slim
tbody id='table_of_people'
  - resource.each do |person|
    tr
      td = link_to "#{person.name}", person
      td = "#{person.description}"
      td = "#{person.birth_date}"
      td = "#{person.death_date}"
      td = "#{Family.find(person.family).surname if person.family.present?}"
      td = "#{Person.find(person.father).name if person.father.present?}"
      td = "#{Person.find(person.mother).name if person.mother.present?}"
      td = "#{Person.find(person.married_on).map{ |p| p.name} if person.married_on.present? && person.married_on[0] != ''}"
      td 
        = link_to 'Удалить', person, data: { turbo_method: :delete, turbo_confirm: 'Вы уверены?' }
        br 
        = link_to 'Изменить', edit_person_path(person)

app/views/people/edit.html.slim
= render 'shared/errors', resource: @person 

= link_to 'Назад', people_path, class: 'btn'

= render 'form'

app/views/people/index.html.slim
h3 Люди
= link_to 'Назад', trees_path, class: 'btn'
p = link_to 'Новый человек', new_person_path, class: 'btn'
div class='single_select'
  = label_tag  :family, 'Семья'
  = select_tag :family, options_from_collection_for_select(@families, :id, :surname), { prompt: "Все" }

table
  thead
    tr
      th ФИО
      th Описание
      th *
      th †
      th Семья
      th Отец
      th Мать
      th Партнер
      th
  = render 'table', resource: @people 

app/views/people/new.html.slim
= render 'shared/errors', resource: @person 

= link_to 'Назад', people_path, class: 'btn'

= render 'form'

app/views/people/show.html.slim
= link_to 'Назад', people_path

h3 = @person.name
p = @person.description

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b = "#{resource.errors.count} error(s) detected: "
  ul
    - resource.errors.full_messages.each do |message|
      li = message

app/views/trees/get_family.js.erb
$('#person_father').empty(); 
$('#person_mother').empty(); 
$('#person_married_on').empty(); 
$('#person_father').append($('<option value="">Выберите</option>'));
$('#person_mother').append($('<option value="">Выберите</option>'));
$('#person_married_on').append($('<option value="">Выберите</option>'));
<% @people.each do |person|%>
  $('#person_father').append($('<option value="<%= person.id %>"> <%= person.name %> </option>'));
  $('#person_mother').append($('<option value="<%= person.id %>"> <%= person.name %> </option>'));
  $('#person_married_on').append($('<option value="<%= person.id %>"> <%= person.name %> </option>'));
  $("#table_of_people tr").remove();
<% end %>

app/views/trees/index.html.slim
h3 Древо
div class='single_select'
  = label_tag  :family, 'Семья'
  = select_tag :family, options_from_collection_for_select(@families, :id, :surname), { prompt: "Выберите" }
p id='info_people'
svg id="svg" class='block'